/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppWalletsRouteImport } from './routes/_app.wallets'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNetworksRouteImport } from './routes/_app.networks'
import { Route as AppFactoryRouteImport } from './routes/_app.factory'
import { Route as AppDistributionRouteImport } from './routes/_app.distribution'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAssetsIdRouteImport } from './routes/_app.assets.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppFactoryRoute = AppFactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/assets': typeof AppAssetsRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/distribution': typeof AppDistributionRoute
  '/factory': typeof AppFactoryRoute
  '/networks': typeof AppNetworksRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/wallets': typeof AppWalletsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/assets/$id': typeof AppAssetsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/assets': typeof AppAssetsRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/distribution': typeof AppDistributionRoute
  '/factory': typeof AppFactoryRoute
  '/networks': typeof AppNetworksRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/wallets': typeof AppWalletsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/assets/$id': typeof AppAssetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/distribution': typeof AppDistributionRoute
  '/_app/factory': typeof AppFactoryRoute
  '/_app/networks': typeof AppNetworksRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/wallets': typeof AppWalletsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$id': typeof AppAssetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assets'
    | '/audit'
    | '/distribution'
    | '/factory'
    | '/networks'
    | '/reports'
    | '/settings'
    | '/users'
    | '/wallets'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/assets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/assets'
    | '/audit'
    | '/distribution'
    | '/factory'
    | '/networks'
    | '/reports'
    | '/settings'
    | '/users'
    | '/wallets'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/assets/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/assets'
    | '/_app/audit'
    | '/_app/distribution'
    | '/_app/factory'
    | '/_app/networks'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/wallets'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/_app/assets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/wallets': {
      id: '/_app/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks': {
      id: '/_app/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factory': {
      id: '/_app/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof AppFactoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distribution': {
      id: '/_app/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$id': {
      id: '/_app/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsIdRoute: typeof AppAssetsIdRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsIdRoute: AppAssetsIdRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppFactoryRoute: typeof AppFactoryRoute
  AppNetworksRoute: typeof AppNetworksRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppFactoryRoute: AppFactoryRoute,
  AppNetworksRoute: AppNetworksRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
